### ISSUE TITLE
openelec找不到视频时无法退出

### ISSUE THREAD

**Issue by ar1zxy** [catro/plugin.video.youkutv#12]
硬盘装的openelec，用鼠标键盘操作，暂时没找到log文件，我先描述一下：

播放前，如果网络不好无法找到视频，过一会儿会提示等待或者取消，如果点击取消，则不会返回之前的界面，还是右下角转动的进度标志，一直转动，除了关机没有其他方法退出。

**Comment by catro** [comment]
应该是解决了
