### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mixboser** [catro/plugin.video.youkutv#17]
Hi,
This plugin was working great but suddenly not working this week. Here is the log.

11:38:50 T:67388  NOTICE: -->Python Interpreter Initialized<--
11:38:51 T:68052   ERROR: Control 510 in window 13000 has been asked to focus, but it can't
11:38:51 T:67388  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/tv/main?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0
11:38:52 T:67388  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/tv/main/top?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0
11:38:52 T:68080  NOTICE: Thread JobWorker start, auto delete: true
11:38:52 T:67388   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
11:38:53 T:67388   ERROR: Previous line repeats 9 times.
11:38:53 T:67388  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/layout/smarttv/play/detail?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0&id=7b4abbd4c0c611e4a080
11:38:54 T:67388  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/common/shows/relate?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0&id=7b4abbd4c0c611e4a080
11:38:58 T:67388   ERROR: EXCEPTION: argument "value" for method "setProperty" must be unicode or str
11:38:58 T:67640   ERROR: Previous line repeats 39 times.
11:38:58 T:67640  NOTICE: Thread JobWorker start, auto delete: true
11:39:04 T:67388  NOTICE: [YouKu TV]Frech: http://v.youku.com/player/getPlayList/VideoIDS/XOTE1NjA1NzMy/ctype/12/ev/1
11:39:05 T:67388  NOTICE: [YouKu TV]Frech: http://api.flvxz.com/token/7eb09609f912fe02bcc9b67d9d0efb42/site/youku/vid/XOTE1NjA1NzMy/jsonp/purejson
11:39:18 T:67388  NOTICE: [YouKu TV]Frech fail
11:39:18 T:67388   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "C:\Users\mixboser\AppData\Roaming\Kodi\addons\plugin.video.youkutv-master\addon.py", line 1654, in onClick
                                                play(self.pdata['videoid'])
                                              File "C:\Users\mixboser\AppData\Roaming\Kodi\addons\plugin.video.youkutv-master\addon.py", line 1997, in play
                                                if item['quality'] == settings_data['flvxz'][quality]:
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--

Thanks.

**Comment by catro** [comment]
最新版改用直接解析视频地址，问题解决了
