### ISSUE TITLE
能加入到中文插件库吗

### ISSUE THREAD

**Issue by taxigps** [catro/plugin.video.youkutv#18]
你的youkutv插件与android应用程序一样，很实用。能把它加入到xbmc-addons-chinese插件库以方便kodi爱好者安装使用吗？

**Comment by catro** [comment]
可以的

**Comment by taxigps** [comment]
已加入插件库，https://github.com/taxigps/xbmc-addons-chinese/commit/d310126c93f0bcad6331a9f89bf991e8510405de
