### ISSUE TITLE
无法正常播放

### ISSUE THREAD

**Issue by liberize** [catro/plugin.video.youkutv#19]
选『分段』和『堆叠』均无法播放，选『m3u8』可播，但是播一会儿后会快进
Kodi 版本 15.1，插件版本 1.6.0，操作系统版本 Raspbian Wheezy

**Comment by catro** [comment]
试了下在windows下可以正常解析。m3u8是kodi播放器本身的问题，这个解决不了。能不能把log文件贴出来我看看是什么问题？

**Comment by liberize** [comment]
@catro log 文件在哪儿？

**Comment by catro** [comment]
这里列了常见的操作系统下的路径，http://kodi.wiki/view/Log_file/Advanced#Location

**Comment by liberize** [comment]
刚才试了一下，原来是没有图像，只有声音，我以为没有反应
好像发现了另外一个问题，无法获取视频信息，比如打开首页那个《云中歌》

17:21:15 T:1600721920  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/layout/smarttv/play/detail?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0&id=e1c378f4b91811e2be40
17:21:15 T:1961631744   DEBUG: Activating window ID: 10138
17:21:15 T:1961631744   DEBUG: ------ Window Init (DialogBusy.xml) ------
17:21:15 T:1600721920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('img',)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.youkutv/addon.py", line 1586, in onInit
                                                self.init()
                                              File "/home/pi/.kodi/addons/plugin.video.youkutv/addon.py", line 1606, in init
                                                self.getControl(701).setImage(data['img'])
                                            KeyError: ('img',)
                                            -->End of Python script error report<--
17:21:15 T:1548743680   DEBUG: webserver: request received for /jsonrpc
17:21:37 T:1684608000   DEBUG: Previous line repeats 11 times.

**Comment by liberize** [comment]
刚才第一次试的时候是正常的，后来不知怎么就刷不出来了

**Comment by liberize** [comment]
网络是正常的，其他插件可以正常工作

**Comment by liberize** [comment]
刚才应该是优酷服务器抽风了，现在好了，没有图像也是 kodi 的问题么？似乎没有 youkutv 相关的 log

**Comment by liberize** [comment]
# pi at raspberrypi in ~ [17:33:16]
$ cat ~/.kodi/temp/kodi.log | grep youku
                                   
17:25:35 T:1961578496   DEBUG: ADDON: cpluff: 'Plug-in plugin.video.youkutv has been installed.'
17:25:36 T:1961578496    INFO: Loading special://masterprofile/keymaps/youkutv.xml
17:25:36 T:1961578496    INFO: Loading special://profile/keymaps/youkutv.xml
17:27:04 T:1667830784 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.youkutv/-poster.jpg
17:27:04 T:1667830784 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.youkutv/-poster.png
17:27:04 T:1667830784 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.youkutv/-banner.jpg
17:27:04 T:1667830784 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.youkutv/-banner.png
17:27:04 T:1667830784 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.youkutv/-fanart.jpg
17:27:04 T:1667830784 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.youkutv/-fanart.png
17:27:06 T:1667830784   DEBUG: CPythonInvoker(6, /home/pi/.kodi/addons/plugin.video.youkutv/addon.py): start processing
17:27:06 T:1667830784   DEBUG: CPythonInvoker(6, /home/pi/.kodi/addons/plugin.video.youkutv/addon.py): the source file to load is "/home/pi/.kodi/addons/plugin.video.youkutv/addon.py"
17:27:06 T:1667830784   DEBUG: CPythonInvoker(6, /home/pi/.kodi/addons/plugin.video.youkutv/addon.py): setting the Python path to /home/pi/.kodi/addons/plugin.video.youkutv:/home/pi/.kodi/addons/script.common.plugin.cache/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PIL:/usr/lib/pymodules/python2.7
17:27:06 T:1667830784   DEBUG: CPythonInvoker(6, /home/pi/.kodi/addons/plugin.video.youkutv/addon.py): entering source directory /home/pi/.kodi/addons/plugin.video.youkutv
17:27:06 T:1667830784   DEBUG: CPythonInvoker(6, /home/pi/.kodi/addons/plugin.video.youkutv/addon.py): instantiating addon using automatically obtained id of "plugin.video.youkutv" dependent on version 0.0.0 of the xbmc.python api
17:27:08 T:1961578496   DEBUG: ------ Window Init (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/main.xml) ------
17:27:08 T:1961578496    INFO: Loading skin file: /home/pi/.kodi/addons/plugin.video.youktv/resources/skins/Default/720p/main.xml, load type: LOAD_ON_GUI_INIT
17:27:08 T:1667830784  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/tv/main?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0
17:27:08 T:1667830784  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/tv/main/top?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0
17:27:16 T:1961578496   DEBUG: ------ Window Deinit (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/main.xml) ------
17:27:16 T:1961578496   DEBUG: ------ Window Init (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/detail.xml) ------
17:27:16 T:1961578496    INFO: Loading skin file: /home/pi/.kodi/addons/plugin.video.youktv/resources/skins/Default/720p/detail.xml, load type: LOAD_ON_GUI_INIT
17:27:16 T:1667830784  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/layout/smarttv/play/detail?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0&id=9fb4364e770f11e5b692
17:27:16 T:1667830784  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/common/shows/relate?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0&id=9fb4364e770f11e5b692
17:27:18 T:1961578496   DEBUG: ------ Window Deinit (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/detail.xml) ------
17:27:18 T:1961578496   DEBUG: ------ Window Init (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/main.xml) ------
17:27:19 T:1961578496   DEBUG: ------ Window Deinit (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/main.xml) ------
17:27:19 T:1961578496   DEBUG: ------ Window Init (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/detail.xml) ------
17:27:19 T:1961578496    INFO: Loading skin file: /home/pi/.kodi/addons/plugin.video.youktv/resources/skins/Default/720p/detail.xml, load type: LOAD_ON_GUI_INIT
17:27:19 T:1667830784  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/layout/smarttv/play/detail?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0&id=e1c378f4b91811e2be40
17:27:20 T:1667830784  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/common/shows/relate?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0&id=e1c378f4b91811e2be40
17:27:57 T:1667830784  NOTICE: [YouKu TV]Frech: http://v.youku.com/player/getPlayList/VideoIDS/XMTM4ODI2NjgwNA==/ctype/12/ev/1
17:27:58 T:1961578496   DEBUG: ------ Window Init (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/confirm.xml) ------
17:27:58 T:1961578496    INFO: Loading skin file: /home/pi/.kodi/addons/plugin.video.youktv/resources/skins/Default/720p/confirm.xml, load type: LOAD_ON_GUI_INIT
17:28:00 T:1961578496   DEBUG: ------ Window Deinit (/home/pi/.kodi/addons/plugin.video.youkutv/resources/skins/Default/720p/confirm.xml) ------
17:28:00 T:1961578496    INFO: easy_aquire - Created session to http://k.youku.com
17:28:00 T:1961578496   DEBUG: CCurlFile::GetMimeType - http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw -> video/flv
17:28:00 T:1961578496   DEBUG: Loading settings for http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw
17:28:00 T:1961578496   DEBUG: CPlayerCoreFactory::GetPlayers(http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw)
17:28:00 T:1961578496  NOTICE: DVDPlayer: Opening: http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw
17:28:00 T:1592333312   DEBUG: CCurlFile::GetMimeType - http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw -> video/flv
17:28:00 T:1592333312   DEBUG: CurlFile::Open(0x64da9740) http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw
17:28:00 T:1592333312   DEBUG: CCurlFile::Open - effective URL: <http://14.18.235.11/youk/695C5882236752FE8945A75/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23.flv>
17:28:00 T:1592333312    INFO: ffmpeg[5EE91400]: Input #0, flv, from 'http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw':
17:28:00 T:1592333312    INFO: ffmpeg[5EE91400]:     metadatacreator : modified by youku.com in 20111202
17:28:00 T:1961578496   DEBUG: CGUIInfoManager::SetCurrentMovie(http://k.youku.com/player/getFlvPath/sid/7447838877491121ed05d_00/st/flv/fileid/0300010E00564AAFA3482D2F22B07CA5FF4843-00EA-0080-016F-4FD21D3CCC23?K=5ef9a40d6d05106d282af50a&hd=1&myp=0&ts=191&ypp=0&ctype=12&ev=1&token=8241&oip=2004996697&ep=dSaQHUGOXsYH4ifWiT8bZnm2dHJbXP4J9h+FgNIXALshTuzO6EigxJm4TItAYPsbACIBY5r03abjYkQXYfBD3BkQ306gOfrg//aV5aklsJIBEhpFAb7Vt1SWQTTw)

**Comment by liberize** [comment]
确定了是 Kodi 的问题，把视频下载下来以后，直接让 Kodi 播放，一样没画面
