### ISSUE TITLE
今天发现已经播放不了

### ISSUE THREAD

**Issue by donly** [catro/plugin.video.youkutv#20]
除了播放，其他正常

**Comment by catro** [comment]
修复好了

**Comment by donly** [comment]
还是播放不了，log：

> 10:27:31 T:140735239786496   DEBUG: ------ Window Init (DialogBusy.xml) ------
10:27:32 T:123145308282880  NOTICE: [YouKu TV]Frech: http://pl.youku.com/playlist/m3u8?vid=XMTQwMDU0OTU0NA%3D%3D&ts=1448936852&ctype=12&token=1971&keyframe=1&sid=94489368412671223a2ab&ev=1&type=hd2&ep=eyaQEkCOUMYE5CHZjz8bZS%2BzdiZdXJZ3kn7C%2FKYHAMRALejB6DPcqJy5Sf4%3D&oip=3698385970
10:27:32 T:123145308282880   ERROR: EXCEPTION: array out of bound
10:27:32 T:123145308282880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: array out of bound
                                            Traceback (most recent call last):
                                              File "/Users/yaokan/Library/Application Support/Kodi/addons/plugin.video.youkutv/addon.py", line 1829, in onClick
                                                play(self.pdata[int(self.getControl(820).getSelectedItem().getLabel2())]['videoid'])
                                              File "/Users/yaokan/Library/Application Support/Kodi/addons/plugin.video.youkutv/addon.py", line 2119, in play
                                                player.play(playlist, arg=vid)
                                              File "/Users/yaokan/Library/Application Support/Kodi/addons/plugin.video.youkutv/addon.py", line 96, in play
                                                if item[0].getfilename() == m3u8_file:
                                            RuntimeError: array out of bound
                                            -->End of Python script error report<--

**Comment by catro** [comment]
哪个视频，清晰度选的是哪个？

**Comment by donly** [comment]
随便点一下，任何一个都播不了

**Comment by catro** [comment]
修复了，你在试试看？

**Comment by donly** [comment]
Awesome!
可以啦〜
谢谢！

**Comment by donly** [comment]
版本：当前的master版本，1.7.3
问题：随便一个视频播放不了
日志：

> 22:39:21 T:140735303229440   DEBUG: ------ Window Init (Pointer.xml) ------
22:39:22 T:140735303229440   DEBUG: ProcessMouse: trying mouse action leftclick
22:39:22 T:123145303990272  NOTICE: [YouKu TV]Frech: http://play.youku.com/play/get.json?vid=XMTQzNTM2MzAzNg==&ct=12
22:39:22 T:140735303229440   DEBUG: Activating window ID: 10138
22:39:22 T:140735303229440   DEBUG: ------ Window Init (DialogBusy.xml) ------
22:39:22 T:123145303990272  NOTICE: [YouKu TV]Frech: http://play.youku.com/play/get.json?vid=XMTQzNTM2MzAzNg==&ct=10
22:39:22 T:140735303229440   DEBUG: ------ Window Init (DialogOK.xml) ------
22:39:23 T:140735303229440   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
22:39:23 T:140735303229440   DEBUG: Keyboard: scancode: 0x00, sym: 0x0136, unicode: 0x0000, modifier: 0x0
22:39:23 T:140735303229440   DEBUG: GetActionCode: Trying Hardy keycode for 0xf200
22:39:23 T:140735303229440   DEBUG: Previous line repeats 1 times.
22:39:23 T:140735303229440   DEBUG: OnKey: 0 (0xf200) pressed, action is
22:39:23 T:140735303229440   DEBUG: ------ Window Deinit (Pointer.xml) ------

**Comment by catro** [comment]
我现在试了下是可以播放的，你再试试，是不是网络问题？

**Comment by donly** [comment]
不是网络问题，应该是旧版本留下的配置问题，我在设置里 *重置选项* 就可以了！
