### ISSUE TITLE
现在无法播放了？

### ISSUE THREAD

**Issue by ufo456** [catro/plugin.video.youkutv#22]
6:55:16 T:5956  NOTICE: [YouKu TV]Frech fail
16:55:18 T:1140   ERROR: Control 820 in window 13002 has been asked to focus, but it can't
16:55:18 T:5956  NOTICE: [YouKu TV]Frech: http://tv.api.3g.youku.com/layout/smarttv/shows/4035f626850211e4b432/series?pid=0ce22bfd5ef5d2c5&guid=12d60728bd267e3e0b6ab4d124d6c5f0&ngdid=357e71ee78debf7340d29408b88c85c4&ver=2.6.0&operator=T-Mobile_310260&network=WIFI&launcher=0
16:55:21 T:5956  NOTICE: [YouKu TV]Frech: http://v.youku.com/player/getPlayList/VideoIDS/XMTM5OTM3MzE2MA==/ctype/12/ev/1

**Comment by catro** [comment]
是不是网络问题？我这可以播放的。如果一直打不开，说一下是哪个剧集，第几集，清晰度，格式

**Comment by ufo456** [comment]
所有的剧集均无法播放，单独打开http://v.youku.com/player/getPlayList/VideoIDS/XMTM5OTM3MzE2MA==/ctype/12/ev/1
提示该网页无法显示。
列表均正常

**Comment by catro** [comment]
你给的链接的确无法打开，但你得告诉我你这个链接是哪个视频，清晰度。我这边是可以播放的，所以有可能是你的网络问题。

**Comment by ufo456** [comment]
非常感谢您的回复。
我打开的是 “秦时明月 tv版 ” 第一集 高清 
请问你使用的是什么网络。不知道用代理可以吗？

**Comment by catro** [comment]
估计你使用的是旧版的插件，最新的是1.6.3

**Comment by ufo456** [comment]
非常的感谢，就是版本的问题。谢谢您的耐心回复。
