### ISSUE TITLE
movies can't play more than 60 minutes

### ISSUE THREAD

**Issue by donly** [catro/plugin.video.youkutv#23]
An movie's time is less than an hour, how to solve this problem?
Thanks.

**Comment by catro** [comment]
This issue is solved in version 1.6.4

**Comment by donly** [comment]
OK, When I use '堆叠' to play movie ''可爱的心', it promotes the error dialog and show '解析地址异常，无法播放', but the '分段' is very well.

**Comment by catro** [comment]
Do you mean '可爱的你' because I didn't find '可爱的心'. I have tried '堆叠' and '分段' for '可爱的你', both work OK. It is suggested to use '分段' since it is much faster. It is possibly a network issue.

**Comment by donly** [comment]
The movie is '可爱的你‘ which in the '热播' page 2. But it doesn't matter, it works very well now with the '分段'.
btw, thanks for your suggestion.

**Comment by donly** [comment]
Hi, cartro,

I find the question is that when play a movie on the Android Kodi, it shows  '解析地址异常，无法播放' error, while OS X Kodi is OK.

**Comment by catro** [comment]
Paste the kodi log please.
