### ISSUE TITLE
atv4上面的kodi播放不了

### ISSUE THREAD

**Issue by ws115** [catro/plugin.video.youkutv#24]
如题，更新到1.7.3后，播放都是网络超时，是否继续。

**Comment by donly** [comment]
是啊，最近很不正常，各种问题

**Comment by catro** [comment]
优酷老是改Cookie算法，无奈啊。已修复https://github.com/catro/plugin.video.youkutv/commit/aa0ca1ccf9d9c9ed64894bbd5df33b95bb475c72

**Comment by donly** [comment]
catro, 您辛苦了！
我写过一点 Python，不知哪里可以帮得上忙，很想助你一臂之力。

**Comment by catro** [comment]
我也是python初学者，你看有什么地方需要修正的就发个PR过来，目前没有开发计划，就解析出问题了做做修复。我写的代码还是一团糟呢，哈
