### ISSUE TITLE
网络超时，是否继续。

### ISSUE THREAD

**Issue by ws115** [catro/plugin.video.youkutv#27]
如题,又这样了

**Comment by donly** [comment]
怎么操作的，我这边没有问题

**Comment by spring6010** [comment]
我也遇到这个问题了,plugin youtu版本是.最新版的. 无法播放,播放的时候提示,网络超时,是否继续,选择是之后,最后返回 网络地址解析错误,无法播放.

**Comment by catro** [comment]
刚试用了下可以正常播放没问题。换几个视频试试是不是网络问题或者会员视频。如果所有视频都不能播放的话把清晰度、语言、地址解析格式和视频名称都贴上来，有log最好

**Comment by spring6010** [comment]
不是会员视频, 所有视频都不能播放, 家里网络是联通的,公司网络是电信的,一样的报错. 版本是1.7.5. kodi版本是15.2 windows版. log怎么取,没找到位置,能给个指引吗,多谢.

**Comment by catro** [comment]
默认位置是，C:\Users\[用户]\AppData\Roaming\Kodi\kodi.log
log贴到http://pastebin.com/或者类似网站
同时把log对应的视频名称和设置里的清晰度、语言、地址解析格式也发上来

**Comment by spring6010** [comment]
http://pastebin.com/y0H179aH
视频名称 特种兵4第一集,超清,国语,分段,

**Comment by catro** [comment]
你先把语言改为默认，我有空了修复下

**Comment by spring6010** [comment]
OK啦,把语言改为默认就能播放了.
