### ISSUE TITLE
解析地址异常，无法播放

### ISSUE THREAD

**Issue by gloxec** [catro/plugin.video.youkutv#28]

**Comment by gloxec** [comment]
不论怎么改语言，改分辨率都是这个样子，所有视频都这样，版本为16最新的

**Comment by gloxec** [comment]
sorry,,,,发现播放方式改为分段一切视频就正常了。。。不过你的菜单选项之类的在我上边全都在偏左侧显示，不能显示齐全，甚至部分菜单地方有文字重叠

**Comment by doraemon2011** [comment]
kodi 16.1 jarvis版本，优酷 tv 1.5.5版本 打开视频还是提示 解析地址异常，无法播放

**Comment by catro** [comment]
最新版本是1.7.6

**Comment by doraemon2011** [comment]
请问作者1.7.6在哪里下载呢。我刚在github下载的是1.6.2版本
