### ISSUE TITLE
1.7.6，网络连接正常，只有声音，没有画面

### ISSUE THREAD

**Issue by fypl2008** [catro/plugin.video.youkutv#30]
只有声音，没有画面，版本1.7.6，所有视频都是，地址解析选分段或堆叠也没有改观，请问是什么原因？该怎么解决？谢谢了

**Comment by fypl2008** [comment]
我是在Kodi 15.2上使用的1.7.6的插件

**Comment by fypl2008** [comment]
尝试使用Kodi 16.1后，依旧如此，只有声音，没有画面

**Comment by catro** [comment]
点设置，重置下配置看看。我测试了下首页的第一个视频，声音、画面都没问题

**Comment by fypl2008** [comment]
非常感谢您的回复。刚刚我尝试在设置-视频-加速里，关掉了OMXPlayer和MMAL两项硬件加速，目前点了几个视频都可以正常播放了。
现在有几个新的问题，希望能麻烦您看一下。
搜索“喀秋莎吉他”，第一个红色背景视频，点击播放依旧只有声音没有画面，但这是返回到初始界面，在观看记录里面点击可以正常播放，搜索“军武次位面”，搜索出的视频直接点击播放没有问题。
另，搜索“军武次位面”，节目选项下，只有第一季和第三季，没有搜索到第二季，麻烦您看一下，这是目前发生的问题，非常感谢。

**Comment by catro** [comment]
我试了那个视频，播放是正常的，有声音有画面。
关于搜索结果，由于是显示的结果是优酷返回的，我没有做过过滤。至于为什么优酷没有返回第二季的结果我也不清楚。。。

**Comment by fypl2008** [comment]
我尝试了多次点击喀秋莎吉他的那个视频，只有一次在声音播放了大概一分钟左右后，出现了画面，其余均只有声音没有画面，现在在观看记录里的所有视频都只有声音了，我尝试退出重进插件之后，又正常了。

**Comment by fypl2008** [comment]
噢，对了，我是在树莓派2上使用的Kodi

**Comment by catro** [comment]
嗯，多数是视频解码问题。可以在PC上试试

**Comment by fypl2008** [comment]
请问有计划加入关联优酷账号的功能吗？让这边的收藏与历史与PC同步。
非常感谢您的回复，目前使用基本正常了，发现问题再来向您请教，非常感谢。

**Comment by catro** [comment]
没有，现在已经停止开发新功能了

**Comment by fypl2008** [comment]
噢，真遗憾，不过非常感谢您开发的这个插件，帮助很大，谢谢

**Comment by catro** [comment]
^^
