### ISSUE TITLE
pi3上播放只有声音，没有图像

### ISSUE THREAD

**Issue by pzxbc** [catro/plugin.video.youkutv#32]
在树莓派3上安装了kodi 15.2后，安装了这个插件。插件能够正常运行，但是点击播放后只有声音没有视频播放图像，还是停留在视频信息页面，求解？

**Comment by catro** [comment]
多数情况是解码器的问题，把log贴出来看看。或者把log里面输出的视频地址直接用kodi播放试试。

**Comment by pzxbc** [comment]
@catro 日志文件贴在[这里](https://gist.github.com/pzxbc/2bd1dc79572e1712c976922afb55bcd4)

**Comment by catro** [comment]
这个问题可能得提交到xbmc上去，不是插件能解决的问题
