### ISSUE TITLE
点击播放后有声音，无画面

### ISSUE THREAD

**Issue by bluaxe** [catro/plugin.video.youkutv#34]
Raspberry Pi 3b OSMC 
Youku TV 1.7.6 版本
偶尔可以播放成功，大多数时候点击播放后画面保持在封面画面，只有声音

**Comment by catro** [comment]
试试将插件设置里的播放模式设置为分段，如果还有问题的话多数是播放器本身解码问题

**Comment by bluaxe** [comment]
播放设置调整为分段后播放成功率提高了很多，但仍然有部分片源播放不了。
待查看具体原因是什么。
